// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLv3gy4B4SMCSfjhmcTA0r4rhH-Oh2R1E',
    appId: '1:477616662151:web:cc0843844dca23692aba22',
    messagingSenderId: '477616662151',
    projectId: 'luna-38309',
    authDomain: 'luna-38309.firebaseapp.com',
    storageBucket: 'luna-38309.firebasestorage.app',
    measurementId: 'G-WRKM09NT55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1nwWU-lUd7cCERN43AcJMZ8z2iPRhh7U',
    appId: '1:477616662151:android:41b2f5ebafa144642aba22',
    messagingSenderId: '477616662151',
    projectId: 'luna-38309',
    storageBucket: 'luna-38309.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGb9NU9sWPZM9WtdACokLO3-26BHPytJI',
    appId: '1:477616662151:ios:b51852e6912f49402aba22',
    messagingSenderId: '477616662151',
    projectId: 'luna-38309',
    storageBucket: 'luna-38309.firebasestorage.app',
    iosBundleId: 'com.ftrance.luna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGb9NU9sWPZM9WtdACokLO3-26BHPytJI',
    appId: '1:477616662151:ios:b51852e6912f49402aba22',
    messagingSenderId: '477616662151',
    projectId: 'luna-38309',
    storageBucket: 'luna-38309.firebasestorage.app',
    iosBundleId: 'com.ftrance.luna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLv3gy4B4SMCSfjhmcTA0r4rhH-Oh2R1E',
    appId: '1:477616662151:web:0876546c3f0a3d602aba22',
    messagingSenderId: '477616662151',
    projectId: 'luna-38309',
    authDomain: 'luna-38309.firebaseapp.com',
    storageBucket: 'luna-38309.firebasestorage.app',
    measurementId: 'G-3CZTMWVD7Q',
  );
}
